# Place to install our libraries to.
# Change to "" if you don't want to auto install.
game_folder: /home/michelle/Halo/Games/Halo Custom Edition/
# If true, VulpesLoader will overwrite strings.dll.
# If false VulpesLoader will end up in the controls folder.
strings_build: true
