# Place to install our libraries to.
# Change to "" if you don't want to auto install.
game_folder: /home/michelle/Halo/Games/Halo Custom Edition/
# If strings, VulpesLoader will overwrite strings.dll.
# If controls VulpesLoader will end up in the controls folder.
# If mods VulpesLoader will end up in the mods folder.
build_type: mods

# These files will get generated into cpp and hpp files.
yaml_files:
    - vulpes/memory/signatures.yaml
    - vulpes/memory/gamestate/object.yaml
    - vulpes/memory/gamestate/object_device.yaml
    - vulpes/memory/gamestate/object_item.yaml
    - vulpes/memory/gamestate/object_unit.yaml
    - vulpes/memory/gamestate/player.yaml
