#define VULPES_AUTHOR "gbMichelle"
#define VULPES_VERSION_MAJOR 0
#define VULPES_VERSION_MINOR 0
#define VULPES_VERSION_PATCH 0

#define VULPES_BUILD_STRING STR(VULPES_VERSION_MAJOR) "." STR(VULPES_VERSION_MINOR) "." STR(VULPES_VERSION_PATCH)
